# Generated by Django 5.0.1 on 2024-01-31 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Choose Subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategory', verbose_name="Product's Subcategory"),
        ),
    ]
